[project]
name = "clean-arch-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mysql-connector-python>=9.4.0",
    "pre-commit>=4.3.0",
    "pymysql>=1.1.1",
    "pytest>=8.4.1",
    "sqlalchemy>=2.0.43",
]
